[build]
  command = "npm install && npm run build"
  functions = "express"

[[redirects]]
  from = '/*'
  to = '/.netlify/functions/:splat'
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"